### ISSUE TITLE
about warmup.py

### ISSUE THREAD

**Issue by liwei1101** [BinhuiXie/SPCL#5]
Thank you for sharing your code!
 I would like to ask why the warm-up phase uses adversarial learning? Isn't fully supervised learning of source domain images used for the warm-up? 
Using the target domain for adversarial learning would introduce noise into the selection of the source domain prototype, wouldn't it!

**Comment by BinhuiXie** [comment]
Hi @liwei1101 

It is a good question. 

Apparently, as you say, there are two common strategies for the warm-up stage, i.e., the fully-supervised source-only model or the AdaptSegNet model. Both have pros and cons. For the source-only model, the model may be overfitting to the source images and the target pseudo labels would be noisy and error-prone. By contrast, I think adversarial alignment between source and target domain would diminish the domain gap and the model could produce more confident target pseudo labels. 

As for source prototypes,  there may be little difference between the above two models. As I see, prototypes that come from AdaptSegNet are better, since the feature space is optimized using source and target data.

**Comment by liwei1101** [comment]
@BinhuiXie Thank you!!

Your explanation has really solved a big question in my mind! 

Have you compared the quantitative performance differences between the two warm-up methods? 

Is the final mIOU in your paper also obtained by the AdaptSegNet warm-up method? Or is it by source domain training only?

**Comment by BinhuiXie** [comment]
In this work, [SPCL](https://arxiv.org/abs/2111.12358), we use the AdaptSegNet model as the warm-up stage. However, it doesn't matter which warm-up strategy is chosen as long as the designed algorithm is effective and robust. 

In our recent work, [SePiCo](https://arxiv.org/abs/2204.08808), we trained the model from scratch and also attained excellent results.

**Comment by liwei1101** [comment]
@BinhuiXie 
Respect!!!

Thank you for your reply, I'll think it over!
